# CI that:
#
# * checks the code is formatted correctly
# * checks the code builds correctly
# * checks that the tests pass
# * checks the code has no clippy lints

name: Check

on: [push, pull_request]

env:
  RUSTFLAGS: "-Dwarnings" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build
  build-announced:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install MSRV
        run: rustup toolchain add 1.82
      - name: Build
        run: cargo +1.82 build
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format
        run: cargo fmt --check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: cargo test
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --all-targets --all-features
